### ISSUE TITLE
New version doesn't work with ext: Inline images in attachment

### ISSUE THREAD

**Issue by ivanovd** [VSEphpbb/lightbox#25]
Hi vse,

The latest version of the lightbox plug for some reason stopped working with another extension that is very useful: Inline images in attachment
By "not working" I mean that the image attachments (or emebedded pictures via bbcode) are opened in the same window without the lightbox effect as though the extension is disabled. If the image is not inline with another one it displays just with lightbox effect.

Name: Inline images in attachment
bb3mobi/inlineimg

phpBB ver is 3.1.6

Lightbox ext version is 1.0.0

**Comment by VSEphpbb** [comment]
Does not work with that extension. It's up to that extension to make it work, as they are the one's breaking away from normal phpBB code convention.
