### ISSUE TITLE
Doesn't work for portrait orientation attachments

### ISSUE THREAD

**Issue by ivanovd** [VSEphpbb/lightbox#26]
Hi vse,

Much respect for your work. Can you please look into the following issue: the lightbox effect doesn't work for portrait orientation attachments, nor external pictures enclosed in [img] tags.

Example:

[Not working]Portrait: http://forum.ladaclub-bg.com/viewtopic.php?p=235627#p235627
[Working] Landscape: http://forum.ladaclub-bg.com/viewtopic.php?p=235634#p235634

phpBB version 3.1.7-pl1
PHP 5.6.11
MySQL 5.5.45-cll

No other attachment related extension are installed:
![untitled20160125121718](https://cloud.githubusercontent.com/assets/4889583/12548239/a5f37106-c35d-11e5-8a93-1ebf6bb2d7b0.png)

Lightbox settings
![untitled20160125122539](https://cloud.githubusercontent.com/assets/4889583/12548416/c6b07b7c-c35e-11e5-9588-6d393a4018da.png)

**Comment by VSEphpbb** [comment]
It's working fine, but post in the extensions support forum... Short answer is your portrait thumbnail is already less wide than 150px so it is ignored by lightbox.

**Comment by VSEphpbb** [comment]
See what this change does for you? 
https://github.com/VSEphpbb/lightbox/pull/27

**Comment by ivanovd** [comment]
Yes, that fixed the issue. Thanks much. I appreciate it.
