### ISSUE TITLE
Lightbox showing errors in Inspect Element

### ISSUE THREAD

**Issue by msayle** [VSEphpbb/lightbox#29]
I uploaded the files to the /ext folder - enabled it - and updated the post settings. 

However, it's not working on my forum [TalkAircraft.com](http://TalkAircraft.com). 

I noticed in inspect element, there are several error related to lightbox. 

Any idea where I went wrong? It seems everything I am using is up to date.

**Comment by VSEphpbb** [comment]
It's not compatible with that theme, and the fault for that lies with the theme developer. They have left out many of the required and built in elements that are needed for this extension (and many others as well) to function properly. Unfortunately that is a paid theme, and the authors of that theme seem to only want to promote their own paid extensions to use with it, so bottom line, you can't use this with that theme.
