### ISSUE TITLE
Resizing affects direct link to posts

### ISSUE THREAD

**Issue by nilaihah** [VSEphpbb/lightbox#34]
Hello there,

Thanks for this extension. Noticed a small but annoying problem with it. When I have resized a large image in a thread, if there are direct links sending people to particular posts in the middle of that same thread (from within the thread itself or anywhere), it instead sends them further down the page, rather than at the start of the post in question (it seems to be where they would be sent if the image was full size).

Example: 
1. Here there is a post with a big image, resized to a thumbnail, and a link to a post down the page:
http://prntscr.com/elxqew

2. Here I clicked the link, and it sent me halfway down the post rather than at the start.
http://prntscr.com/elxs89 (you can see the browser address bar at the top. This is where the link sent me in the thread)

3. If I scroll back up to the top post, and click the link again, then it sends me correctly to the right place at the start of that post: http://prntscr.com/elxse5

If I remove the extension completely, or remove the image, or remove the resizing, then the links again work as expected.

**Comment by VSEphpbb** [comment]
That's an issue with your browser. Your browser isn't smart enough to realize the page has changed since it first opened, which it will because the mage was resized. There is nothing that can be done about that, other than complain to your browser maker that they should be aware of anchor points after a page's layout has changed.

**Comment by nilaihah** [comment]
Is there any browser where this doesn't happen? Tried latest version of Firefox and Chrome.
