### ISSUE TITLE
suggestions ?

### ISSUE THREAD

**Issue by exxosuk** [VSEphpbb/lightbox#36]
Hi, I cannot the life of me see any way to contact you about this extension :(

I actually wanted to ask if it is possible, or could be added in the future, to override the settings in the control panel, for individual images on the forum.

For example I limit some image with to say 400 PX, but may actually have an image which is 450 PX which could actually be allowed, and looks pretty awful when it is resize. 

While I could up the image size to 450 PX, I really do not want to do this as images on the forum start getting too large the posts. It is also a similar problem that some images may actually be 500 PX, and then resize to 450. Whereas if the image height is not very tall, then full width could actually be allowed on the forum.

But in some cases it would be really useful to have some sort of in-line command to turn off image resizing with the lightbox extension. And selected images could be displayed in the posts full-size when required.

**Comment by VSEphpbb** [comment]
https://www.phpbb.com/customise/db/extension/lightbox/support
