### ISSUE TITLE
Incompatiblity with Hotschi Download Extension

### ISSUE THREAD

**Issue by panteror** [VSEphpbb/lightbox#38]
Hi,

There is a problem with lightbox and Hotschi Download Extension on 3.2.
https://github.com/oxpus/Download-32-Extension

On each download page, lightbox is displayed on footer "empty square" , see screenshot.

![dowfrance communaute francophone days of war downloads](https://user-images.githubusercontent.com/13719235/32557094-7ddc851c-c4a1-11e7-9022-4ba33dd34539.png)

Thanks

**Comment by oxpus** [comment]
Can you please post the link for the lightbox package to take some tests?
Currently I've no solution about this error.

**Comment by oxpus** [comment]
Please try the following:
Open the file
/ext/oxpus/dlext/includes/modules/dl_footer.php
find the row
		'DL_MOD_RELEASE'		=> $this->language->lang('DL_MOD_VERSION_PUBLIC'),
and add after this
		'LIGHTBOX_RESIZE_WIDTH'	=> 0,

In my develoment forum the lightbox will be disabled within the complete download area.

**Comment by panteror** [comment]
Hi,
This solution seems working, I have no more the lightbox square area in footer.
Thanks.

**Comment by panteror** [comment]
Hi,
This solution seems working, I have no more the lightbox square area in
footer.
Thanks.

2017-11-11 17:56 GMT+01:00 Karsten Ude <notifications@github.com>:
