### ISSUE TITLE
Navigation among images

### ISSUE THREAD

**Issue by Galixte** [VSEphpbb/lightbox#4]
Hi,

with the "Lightbox 2 jQuery" plugin it's possible to configure any image sets, to navigate among images.

How to make the same thing in a message with attachments like images ?

**Comment by VSEphpbb** [comment]
Change this line to true:
https://github.com/VSEphpbb/lightbox/blob/master/styles/all/template/event/overall_footer_after.html#L8

**Comment by Galixte** [comment]
Thanks for help !
