### ISSUE TITLE
Debugging error

### ISSUE THREAD

**Issue by newbeetle** [VSEphpbb/lightbox#40]
Impossible de retrouver https://www.forum-newbeetle.fr/ext/vse/lightbox/styles/all/template/src/js/lightbox.js spécifié dans le mappage de source https://www.forum-newbeetle.fr/ext/vse/lightbox/styles/all/template/lightbox/js/lightbox.min.map.

**Comment by VSEphpbb** [comment]
http://lokeshdhakar.com/projects/lightbox2/
